server:
  port: 8989

second:
  server:
    host: localhost
    port: 9091
    protocol: http
    api-token: c276558aab1cb2462c613aeca8a61301d20a0cff12e0717c3e5698b5396ae044caf72678ed3f59c7f5ab58605ec9def97f886cbb1107853c4ddadee5c7f32a9c


spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.4:41521:xe
    username: C##INFOMATE
    password: INFOMATE
    hikari:
      auto-commit: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  web:
    resources:
      static-locations: classpath:/productimgs/

  jpa:
    generate-ddl: false
    show-sql: true
    database: oracle
#        hibernate:
#          ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        temp:
          use_jdbc_metadata_defaults: false
  data:
    web:
      pageable:
        default-page-size: 20 #페이지 사이즈(default)
        max-page-size: 50 # max 사이즈

  profiles:
    active: local

jwt:
  secret: 1LxrVXYDdRoBBa2Wc9lfOLVUl9BXt6JEZEhkm1mLY04lbjIx4I18x4QOha7cSKrCQJCKwpavnVtfVzFPnBzJfQ==

logging:
  level:
    root: info
    org:
#      hibernate:
#        SQL: debug
#        type: trace

image:
  add-resource-locations: classpath:/static/productimgs/
  add-resource-handler: /productimgs/**


#  image-dir: src/main/resources/static/productimgs
#  image-url: http://localhost:8989/productimgs/

  image-dir: C:/dev/02_subSources/img/
  image-url: http://localhost:8989/imgs/


files:
  add-resource-locations: classpath:/static/files/
  add-resource-handler: /files/document/**
  files-dir: src/main/resources/static/files
  files-url: http://localhost:8989/file/download/
