CREATE TABLE TBL_CHATROOM
(
    CHATROOM_CODE    NUMBER NOT NULL,
    CHATROOM_NAME    VARCHAR2(255) NOT NULL,
    CHATROOM_CREATE_DATE  TIMESTAMP NOT NULL
);

COMMENT ON COLUMN TBL_CHATROOM.CHATROOM_CODE IS '채팅방코드';

COMMENT ON COLUMN TBL_CHATROOM.CHATROOM_NAME IS '채팅방명';

COMMENT ON COLUMN TBL_CHATROOM.CHATROOM_CREATE_DATE IS '채팅방생성일';

COMMENT ON TABLE TBL_CHATROOM IS '채팅방테이블';

CREATE UNIQUE INDEX 채팅방테이블_PK ON TBL_CHATROOM
    ( CHATROOM_CODE );

ALTER TABLE TBL_CHATROOM
    ADD CONSTRAINT 채팅방테이블_PK PRIMARY KEY ( CHATROOM_CODE )
        USING INDEX 채팅방테이블_PK;


CREATE TABLE TBL_CHATROOM_MEMBER_LIST
(
    CHATROOM_CODE    NUMBER NOT NULL,
    MEMBER_CODE    NUMBER NOT NULL
);

COMMENT ON COLUMN TBL_CHATROOM_MEMBER_LIST.REF_CHATROOM_CODE IS '채팅방코드';

COMMENT ON COLUMN TBL_CHATROOM_MEMBER_LIST.MEMBER_CODE IS '멤버코드';

COMMENT ON TABLE TBL_CHATROOM_MEMBER_LIST IS '채팅방멤버정보';

CREATE UNIQUE INDEX TBL_CHATROOM_MEMBER_LIST_PK ON TBL_CHATROOM_MEMBER_LIST
    ( REF_CHATROOM_CODE, REF_MEMBER_CODE );

ALTER TABLE TBL_CHATROOM_MEMBER_LIST
    ADD CONSTRAINT TBL_CHATROOM_MEMBER_LIST_PK PRIMARY KEY ( REF_CHATROOM_CODE, REF_MEMBER_CODE ) USING INDEX TBL_CHATROOM_MEMBER_LIST_PK;




ALTER TABLE TBL_CHATROOM
    ADD CONSTRAINT TBL_POST_BOARD_CODE_FK FOREIGN KEY (BOARD_CODE) REFERENCES TBL_BOARD (BOARD_CODE);